<a href="https://colab.research.google.com/github/mahimasahu/Laboratory-practice-3/blob/main/ass3_Churn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import pandas as pd
import math
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
from google.colab import files
uploded = files.upload()


Saving Churn_Modelling - Churn_Modelling.csv to Churn_Modelling - Churn_Modelling.csv


In [4]:
import io
df = pd.read_csv(io.BytesIO(uploded['Churn_Modelling - Churn_Modelling.csv']))
df.shape

(10000, 14)

In [5]:
df.drop(['CustomerId','RowNumber','Surname'], axis = 'columns', inplace =True)

df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
df.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [7]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [8]:
#one hot encoding
df = pd.get_dummies(data = df, columns=['Geography'])
df.dtypes

CreditScore            int64
Gender                object
Age                    int64
Tenure                 int64
Balance              float64
NumOfProducts          int64
HasCrCard              int64
IsActiveMember         int64
EstimatedSalary      float64
Exited                 int64
Geography_France       uint8
Geography_Germany      uint8
Geography_Spain        uint8
dtype: object

In [9]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [10]:
df['Gender'].replace(['Male', 'Female'],[1, 0], inplace= True)

In [11]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [12]:
#separate outcome or target col
X = df.drop(['Exited'], axis=1)
y = df['Exited']

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
#
# feature scaling
#
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

import tensorflow as tf
from tensorflow import keras

In [14]:
model = keras.Sequential([
    keras.layers.Dense(12, input_shape=(12,),activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])


In [15]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100)


Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5165 - accuracy: 0.7569
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4289 - accuracy: 0.8077
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4077 - accuracy: 0.8165
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3913 - accuracy: 0.8329
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3772 - accuracy: 0.8411
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3652 - accuracy: 0.8489
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3574 - accuracy: 0.8531
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3518 - accuracy: 0.8551
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3478 - accuracy: 0.8561
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3445 - accura

In [16]:
model.evaluate(X_test, y_test)

63/63 [==============================] - 1s 3ms/step - loss: 0.3396 - accuracy: 0.8610


[0.33959224820137024, 0.8610000014305115]

In [17]:
yp = model.predict(X_test)

63/63 [==============================] - 0s 3ms/step


In [29]:
from sklearn.metrics import confusion_matrix , classification_report
#print(classification_report(y_test,yp))

In [19]:
y_pred = []
for element in yp:
    if element > 0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)

In [22]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.92      1595
           1       0.72      0.51      0.60       405

    accuracy                           0.86      2000
   macro avg       0.80      0.73      0.76      2000
weighted avg       0.85      0.86      0.85      2000



In [23]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=y_pred)

cm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1515,   80],
       [ 198,  207]], dtype=int32)>

In [24]:
tf.math.confusion_matrix(labels=y_test,predictions=y_pred)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1515,   80],
       [ 198,  207]], dtype=int32)>